const mysql = require('mysql2')

const DB = mysql.createConnection({
  host: 'JOKE143',
  port: 3306,
  user: 'root',
  password: 'brac1234@#',
  database: 'footballdb',
  waitForConnections: true,
  connectionLimit: 10,
  queueLimit: 0,
})
const table = [
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg',
    0,
    0,
    'Real Madrid CF',
    1902,
    'Santiago Bernabéu Stadium',
    0,
    14,
    35,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/d/d0/Logo_of_AC_Milan.svg',
    0,
    0,
    'AC Milan',
    1899,
    'San Siro',
    0,
    7,
    19,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg',
    0,
    0,
    'FC Barcelona',
    1899,
    'Camp Nou',
    0,
    5,
    27,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg',
    0,
    0,
    'Manchester United',
    1878,
    'Old Trafford',
    0,
    3,
    20,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg',
    0,
    0,
    'Liverpool',
    1892,
    'Anfield',
    0,
    6,
    19,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg',
    0,
    0,
    'Chelsea',
    1905,
    'Stamford Bridge',
    0,
    2,
    6,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
    0,
    0,
    'Arsenal',
    1886,
    'Emirates Stadium',
    0,
    0,
    13,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg',
    0,
    0,
    'Manchester City',
    1880,
    'Etihad Stadium',
    0,
    1,
    9,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg',
    0,
    0,
    'Tottenham Hotspur',
    1882,
    'Tottenham Hotspur Stadium',
    0,
    0,
    2,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg',
    0,
    0,
    'Everton',
    1878,
    'Goodison Park',
    0,
    0,
    9,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_logo.svg',
    0,
    0,
    'Atlético Madrid',
    1903,
    'Wanda Metropolitano',
    0,
    0,
    11,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/3/3c/Sevilla_FC_logo.svg',
    0,
    0,
    'Sevilla FC',
    1890,
    'Ramón Sánchez Pizjuán Stadium',
    0,
    0,
    1,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/c/ce/Valencia_CF_logo.svg',
    0,
    0,
    'Valencia CF',
    1919,
    'Mestalla Stadium',
    0,
    0,
    6,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/9/9e/Real_Betis_logo.svg',
    0,
    0,
    'Real Betis',
    1907,
    'Benito Villamarín Stadium',
    0,
    0,
    1,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/3/3e/Real_Sociedad_logo.svg',
    0,
    0,
    'Real Sociedad',
    1909,
    'Anoeta Stadium',
    0,
    0,
    2,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/1/1e/Athletic_Bilbao_logo.svg',
    0,
    0,
    'Athletic Bilbao',
    1898,
    'San Mamés Stadium',
    0,
    0,
    8,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/4/4e/Villarreal_CF_logo.svg',
    0,
    0,
    'Villarreal CF',
    1923,
    'Estadio de la Cerámica',
    0,
    0,
    0,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/9/9f/RC_Celta_de_Vigo_logo.svg',
    0,
    0,
    'Celta Vigo',
    1923,
    'Abanca-Balaídos',
    0,
    0,
    0,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/1/1f/FC_Bayern_Munich_logo_%282017%29.svg',
    0,
    0,
    'Bayern Munich',
    1900,
    'Allianz Arena',
    0,
    6,
    33,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/6/67/Borussia_Dortmund_logo.svg',
    0,
    0,
    'Borussia Dortmund',
    1909,
    'Signal Iduna Park',
    0,
    1,
    8,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg',
    0,
    0,
    'RB Leipzig',
    2009,
    'Red Bull Arena',
    0,
    0,
    0,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/6/6d/Bayer_04_Leverkusen_logo.svg',
    0,
    0,
    'Bayer Leverkusen',
    1904,
    'BayArena',
    0,
    0,
    0,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/6/64/1._FC_K%C3%B6ln_logo.svg',
    0,
    0,
    '1. FC Köln',
    1948,
    'RheinEnergieStadion',
    0,
    0,
    3,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/6/6d/FC_Schalke_04_logo.svg',
    0,
    0,
    'Schalke 04',
    1904,
    'Veltins-Arena',
    0,
    0,
    7,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/4/4e/VfL_Wolfsburg_logo.svg',
    0,
    0,
    'VfL Wolfsburg',
    1945,
    'Volkswagen Arena',
    0,
    0,
    1,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/0/0e/Eintracht_Frankfurt_Logo.svg',
    0,
    0,
    'Eintracht Frankfurt',
    1899,
    'Deutsche Bank Park',
    0,
    0,
    1,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/1/1e/Hertha_BSC_Logo_2012.svg',
    0,
    0,
    'Hertha BSC',
    1892,
    'Olympiastadion Berlin',
    0,
    0,
    2,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/3/3f/SC_Freiburg_logo.svg',
    0,
    0,
    'SC Freiburg',
    1904,
    'Europa-Park Stadion',
    0,
    0,
    0,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/2/2d/Juventus_Turin.svg',
    0,
    0,
    'Juventus',
    1897,
    'Allianz Stadium',
    0,
    2,
    36,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/d/d0/Logo_of_AC_Milan.svg',
    0,
    0,
    'AC Milan',
    1899,
    'San Siro',
    0,
    7,
    19,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/0/0b/FC_Internazionale_Milano_2021.svg',
    0,
    0,
    'Inter Milan',
    1908,
    'San Siro',
    0,
    3,
    19,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg',
    0,
    0,
    'AS Roma',
    1927,
    'Stadio Olimpico',
    0,
    0,
    3,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/2/2d/SSC_Napoli_logo.svg',
    0,
    0,
    'Napoli',
    1926,
    'Stadio Diego Armando Maradona',
    0,
    0,
    3,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/0/0e/SS_Lazio_badge.svg',
    0,
    0,
    'Lazio',
    1900,
    'Stadio Olimpico',
    0,
    0,
    2,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/0/0e/ACF_Fiorentina_crest.svg',
    0,
    0,
    'Fiorentina',
    1926,
    'Stadio Artemio Franchi',
    0,
    0,
    2,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/1/1e/Atalanta_BC_logo.svg',
    0,
    0,
    'Atalanta BC',
    1907,
    'Gewiss Stadium',
    0,
    0,
    0,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/4/4b/Bologna_FC_logo.svg',
    0,
    0,
    'Bologna FC',
    1909,
    "Stadio Renato Dall'Ara",
    0,
    0,
    7,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/2/2e/Torino_FC_logo.svg',
    0,
    0,
    'Torino FC',
    1906,
    'Stadio Olimpico Grande Torino',
    0,
    0,
    7,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/4/4d/U.C._Sampdoria_logo.svg',
    0,
    0,
    'Sampdoria',
    1946,
    'Stadio Luigi Ferraris',
    0,
    0,
    1,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/commons/5/5f/Paris_Saint-Germain_FC_logo.svg',
    0,
    0,
    'Paris Saint-Germain',
    1970,
    'Parc des Princes',
    0,
    1,
    11,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/commons/1/1d/Olympique_Lyonnais_logo.svg',
    0,
    0,
    'Olympique Lyonnais',
    1950,
    'Groupama Stadium',
    0,
    0,
    7,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/commons/4/4b/Olympique_de_Marseille_logo.svg',
    0,
    0,
    'Olympique de Marseille',
    1899,
    'Orange Vélodrome',
    0,
    0,
    9,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/commons/1/1b/AS_Monaco_logo.svg',
    0,
    0,
    'AS Monaco',
    1924,
    'Stade Louis II',
    0,
    0,
    8,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/commons/4/4e/Lille_OSC_logo.svg',
    0,
    0,
    'Lille OSC',
    1944,
    'Stade Pierre-Mauroy',
    0,
    0,
    4,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/commons/2/2e/AS_Saint-Étienne_logo.svg',
    0,
    0,
    'AS Saint-Étienne',
    1933,
    'Stade Geoffroy-Guichard',
    0,
    0,
    10,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/commons/1/1a/OGC_Nice_logo.svg',
    0,
    0,
    'OGC Nice',
    1904,
    'Allianz Riviera',
    0,
    0,
    4,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/commons/4/4b/FC_Nantes_logo.svg',
    0,
    0,
    'FC Nantes',
    1943,
    'Stade de la Beaujoire',
    0,
    0,
    8,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/commons/0/0f/RC_Lens_logo.svg',
    0,
    0,
    'RC Lens',
    1906,
    'Stade Bollaert-Delelis',
    0,
    0,
    1,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/commons/4/4f/Stade_Rennais_FC_logo.svg',
    0,
    0,
    'Stade Rennais FC',
    1901,
    'Roazhon Park',
    0,
    0,
    0,
  ][
    ('Netherlands',
    'https://upload.wikimedia.org/wikipedia/commons/6/6e/Ajax_Amsterdam_logo.svg',
    0,
    0,
    'Ajax Amsterdam',
    1900,
    'Johan Cruyff Arena',
    0,
    0,
    36)
  ],
  [
    'Netherlands',
    'https://upload.wikimedia.org/wikipedia/commons/4/4e/PSV_Eindhoven_logo.svg',
    0,
    0,
    'PSV Eindhoven',
    1913,
    'Philips Stadion',
    0,
    0,
    24,
  ],
  [
    'Netherlands',
    'https://upload.wikimedia.org/wikipedia/commons/4/4d/Feyenoord_logo.svg',
    0,
    0,
    'Feyenoord',
    1908,
    'De Kuip',
    0,
    0,
    15,
  ],
  [
    'Netherlands',
    'https://upload.wikimedia.org/wikipedia/commons/4/4b/FC_Utrecht_logo.svg',
    0,
    0,
    'FC Utrecht',
    1970,
    'Stadion Galgenwaard',
    0,
    0,
    0,
  ],
  [
    'Netherlands',
    'https://upload.wikimedia.org/wikipedia/commons/5/5f/FC_Gr%C3%B6nigen_logo.svg',
    0,
    0,
    'FC Groningen',
    1971,
    'Euroborg',
    0,
    0,
    0,
  ],
]
const tableData = (array) => {
  sql =
    'INSERT INTO Club (Country, logo_url, League_id, Manager_id, club_name, Founded_year, Stadium, user_id, ucl_num, league_trophy_num) VALUES ?'
  DB.query(sql, [array], (err, results) => {
    if (err) throw err
    console.log('Success')
  })
}

const Change = (arr) => {
  let newArr = []
  for (let index = 0; index < arr.length; index++) {
    if (arr[index]) {
      const element = arr[index]
      let a = element[0]
      let b = element[1]
      let c = null
      let d = null
      let e = element[4]
      let f = element[5]
      let g = element[6]
      let h = null
      let i = element[8]
      let j = element[9]
      newArr.push([a, b, c, d, e, f, g, h, i, j])
    }
  }
  return newArr
}

changeedArr = Change(table)
tableData(changeedArr)
