const mysql = require('mysql2')

const DB = mysql.createConnection({
  host: 'JOKE143',
  port: 3306,
  user: 'root',
  password: 'brac1234@#',
  database: 'footballdb',
  waitForConnections: true,
  connectionLimit: 10,
  queueLimit: 0,
})
const table = [
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg',
    0,
    0,
    'Real Madrid CF',
    1902,
    'Santiago Bernabéu Stadium',
    0,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/d/d0/Logo_of_AC_Milan.svg',
    0,
    0,
    'AC Milan',
    1899,
    'San Siro',
    0,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg',
    0,
    0,
    'Liverpool FC',
    1892,
    'Anfield',
    0,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/1/1f/FC_Bayern_München_logo_%282017%29.svg',
    0,
    0,
    'FC Bayern Munich',
    1900,
    'Allianz Arena',
    0,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg',
    0,
    0,
    'FC Barcelona',
    1899,
    'Camp Nou',
    0,
  ],
  [
    'Netherlands',
    'https://upload.wikimedia.org/wikipedia/en/7/79/Ajax_Amsterdam.svg',
    0,
    0,
    'AFC Ajax',
    1900,
    'Johan Cruyff Arena',
    0,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg',
    3,
    7,
    'Manchester United FC',
    1878,
    'Old Trafford',
    7,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/0/0c/Inter_Milan.svg',
    2,
    8,
    'Inter Milan',
    1908,
    'San Siro',
    8,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg',
    3,
    9,
    'Chelsea FC',
    1905,
    'Stamford Bridge',
    9,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/d/d2/Juventus_FC_2017_logo.svg',
    2,
    10,
    'Juventus FC',
    1897,
    'Allianz Stadium',
    10,
  ],
  [
    'Portugal',
    'https://upload.wikimedia.org/wikipedia/en/8/81/S.L._Benfica_logo.svg',
    6,
    11,
    'SL Benfica',
    1904,
    'Estádio da Luz',
    11,
  ],
  [
    'Portugal',
    'https://upload.wikimedia.org/wikipedia/en/f/fc/FC_Porto.svg',
    6,
    12,
    'FC Porto',
    1893,
    'Estádio do Dragão',
    12,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/0/0c/Nottingham_Forest_logo.svg',
    3,
    13,
    'Nottingham Forest FC',
    1865,
    'City Ground',
    13,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/6/67/Borussia_Dortmund_logo.svg',
    4,
    14,
    'Borussia Dortmund',
    1909,
    'Signal Iduna Park',
    14,
  ],
  [
    'Scotland',
    'https://upload.wikimedia.org/wikipedia/en/1/1c/Celtic_FC.svg',
    7,
    15,
    'Celtic FC',
    1887,
    'Celtic Park',
    15,
  ],
  [
    'Netherlands',
    'https://upload.wikimedia.org/wikipedia/en/2/2f/PSV_Eindhoven.svg',
    5,
    16,
    'PSV Eindhoven',
    1913,
    'Philips Stadion',
    16,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg',
    8,
    17,
    'Paris Saint-Germain',
    1970,
    'Parc des Princes',
    17,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg',
    3,
    18,
    'Arsenal FC',
    1886,
    'Emirates Stadium',
    18,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg',
    2,
    19,
    'AS Roma',
    1927,
    'Stadio Olimpico',
    19,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/5/56/Atletico_Madrid_2017_logo.svg',
    1,
    20,
    'Atlético Madrid',
    1903,
    'Wanda Metropolitano',
    20,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/0/0a/FC_Schalke_04_logo.svg',
    4,
    21,
    'FC Schalke 04',
    1904,
    'Veltins-Arena',
    21,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/6/6e/Bayer_04_Leverkusen_logo.svg',
    4,
    22,
    'Bayer 04 Leverkusen',
    1904,
    'BayArena',
    22,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/en/f/fd/Olympique_Marseille_logo.svg',
    8,
    23,
    'Olympique de Marseille',
    1899,
    'Stade Vélodrome',
    23,
  ],
  [
    'Netherlands',
    'https://upload.wikimedia.org/wikipedia/en/2/2e/Feyenoord_logo.svg',
    5,
    24,
    'Feyenoord',
    1908,
    'De Kuip',
    24,
  ],
  [
    'Germany',
    'https://upload.wikimedia.org/wikipedia/en/9/95/Eintracht_Frankfurt_Logo.svg',
    4,
    25,
    'Eintracht Frankfurt',
    1899,
    'Deutsche Bank Park',
    25,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg',
    3,
    26,
    'Tottenham Hotspur FC',
    1882,
    'Tottenham Hotspur Stadium',
    26,
  ],
  [
    'Spain',
    'https://upload.wikimedia.org/wikipedia/en/4/4e/Sevilla_FC_logo.svg',
    1,
    27,
    'Sevilla FC',
    1890,
    'Ramón Sánchez Pizjuán Stadium',
    27,
  ],
  [
    'Italy',
    'https://upload.wikimedia.org/wikipedia/en/7/76/ACF_Fiorentina_crest.svg',
    2,
    28,
    'ACF Fiorentina',
    1926,
    'Stadio Artemio Franchi',
    28,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/0/0e/Leeds_United_Logo.svg',
    3,
    29,
    'Leeds United FC',
    1919,
    'Elland Road',
    29,
  ],
  [
    'Portugal',
    'https://upload.wikimedia.org/wikipedia/en/4/47/Sporting_CP_logo.svg',
    6,
    30,
    'Sporting CP',
    1906,
    'Estádio José Alvalade',
    30,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/en/c/c6/Olympique_Lyonnais.svg',
    5,
    32,
    'Olympique Lyonnais',
    1950,
    'Groupama Stadium',
    32,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/en/6/6f/AS_Monaco_FC.svg',
    5,
    33,
    'AS Monaco FC',
    1924,
    'Stade Louis II',
    33,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/en/5/5e/Stade_Rennais_FC.svg',
    5,
    34,
    'Stade Rennais FC',
    1901,
    'Roazhon Park',
    34,
  ],
  [
    'France',
    'https://upload.wikimedia.org/wikipedia/en/3/3e/LOSC_Lille_logo.svg',
    5,
    35,
    'LOSC Lille',
    1944,
    'Stade Pierre-Mauroy',
    35,
  ],
  [
    'USA',
    'https://upload.wikimedia.org/wikipedia/en/d/d2/Inter_Miami_CF_logo.svg',
    6,
    91,
    'Inter Miami CF',
    2018,
    'DRV PNK Stadium',
    36,
  ],
  [
    'Argentina',
    'https://upload.wikimedia.org/wikipedia/en/6/65/Boca_Juniors_logo.svg',
    7,
    92,
    'Boca Juniors',
    1905,
    'La Bombonera',
    37,
  ],
  [
    'Brazil',
    'https://upload.wikimedia.org/wikipedia/en/2/2e/CR_Flamengo_logo.svg',
    8,
    93,
    'CR Flamengo',
    1895,
    'Maracanã Stadium',
    38,
  ],
  [
    'Netherlands',
    'https://upload.wikimedia.org/wikipedia/en/7/79/Ajax_Amsterdam.svg',
    9,
    94,
    'AFC Ajax',
    1900,
    'Johan Cruyff Arena',
    39,
  ],
  [
    'Portugal',
    'https://upload.wikimedia.org/wikipedia/en/8/81/S.L._Benfica_logo.svg',
    10,
    95,
    'SL Benfica',
    1904,
    'Estádio da Luz',
    40,
  ],
  [
    'Turkey',
    'https://upload.wikimedia.org/wikipedia/en/3/3d/Galatasaray_S.K._logo.svg',
    11,
    96,
    'Galatasaray SK',
    1905,
    'Türk Telekom Stadium',
    41,
  ],
  [
    'Russia',
    'https://upload.wikimedia.org/wikipedia/en/1/1c/FC_Zenit_Saint_Petersburg_logo.svg',
    12,
    97,
    'FC Zenit Saint Petersburg',
    1925,
    'Gazprom Arena',
    42,
  ],
  [
    'Mexico',
    'https://upload.wikimedia.org/wikipedia/en/1/1f/Club_América_logo.svg',
    13,
    98,
    'Club América',
    1916,
    'Estadio Azteca',
    43,
  ],
  [
    'South Africa',
    'https://upload.wikimedia.org/wikipedia/en/3/3e/Kaizer_Chiefs_logo.svg',
    14,
    99,
    'Kaizer Chiefs FC',
    1970,
    'FNB Stadium',
    44,
  ],
  [
    'Japan',
    'https://upload.wikimedia.org/wikipedia/en/9/9e/Kashima_Antlers_logo.svg',
    15,
    100,
    'Kashima Antlers',
    1947,
    'Kashima Soccer Stadium',
    45,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/4/4e/Sheffield_United_FC_logo.svg',
    1,
    18,
    'Sheffield United FC',
    1889,
    'Bramall Lane',
    46,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/e/e0/Burnley_FC_badge.png',
    1,
    19,
    'Burnley FC',
    1882,
    'Turf Moor',
    47,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/0/05/Luton_Town_FC_logo.svg',
    1,
    20,
    'Luton Town FC',
    1885,
    'Kenilworth Road',
    48,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/3/31/Aston_Villa_FC_crest_%282016%29.svg',
    1,
    11,
    'Aston Villa FC',
    1874,
    'Villa Park',
    49,
  ],
  [
    'England',
    'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg',
    1,
    5,
    'Tottenham Hotspur FC',
    1882,
    'Tottenham Hotspur Stadium',
    50,
  ],
]

const tableData = (array) => {
  sql =
    'INSERT INTO Club (Country, logo_url, League_id, Manager_id, club_name, Founded_year, Stadium, user_id) VALUES ?'
  DB.query(sql, [array], (err, results) => {
    if (err) throw err
    console.log('Success')
  })
}

const Change = (arr) => {
  const x = arr.map((element) => {
    let a = element[0]
    let b = element[1]
    let c = null
    let d = null
    let e = element[4]
    let f = element[5]
    let g = element[6]
    let h = null
    console.log([a, b, c, d, e, f, g, h])
    return [a, b, c, d, e, f, g, h]
  })
  return x
}

changeedArr = Change(table)
tableData(changeedArr)
